---
.catalog:
  name: "Registry"
  version: "v2.0.0-7"
  description: "Docker Registry stack"
  uuid: registry-7
  minimum_rancher_version: v0.44.0
  questions:
    - variable: "REGISTRY_SSL_KEY"
      label: "Registry key"
      description: "Registry SSL private key"
      type: "multiline"
      required: true
    - variable: "REGISTRY_SSL_CRT"
      label: "Registry certificate"
      description: "Registry SSL certificate"
      type: "multiline"
      required: true
    - variable: "AUTH_SSL_KEY"
      label: "Registry auth key"
      description: "Registry authentication SSL private key"
      type: "multiline"
      required: true
    - variable: "AUTH_SSL_CRT"
      label: "Registry auth certificate"
      description: "Registry authentication SSL certificate"
      type: "multiline"
      required: true
    - variable: "SWIFT_USERNAME"
      label: "Swift username"
      description: "Registry storage Swift username"
      type: "string"
      required: false
    - variable: "SWIFT_PASSWORD"
      label: "Swift password"
      description: "Registry storage Swift password"
      type: "password"
      required: false
    - variable: "SWIFT_AUTH_URL"
      label: "Swift auth URL"
      description: "Registry storage Swift auth URL"
      type: "string"
      required: false
      default: "https://auth.cloud.ovh.net/v2.0"
    - variable: "SWIFT_TENANT_NAME"
      label: "Swift tenant name"
      description: "Registry storage Swift tenant name"
      type: "string"
      required: false
    - variable: "SWIFT_CONTAINER"
      label: "Swift container"
      description: "Registry storage Swift container"
      type: "string"
      required: false
    - variable: "SWIFT_REGION"
      label: "Swift region"
      description: "Registry storage Swift region"
      type: "string"
      required: false
    - variable: "GITHUB_ORGANIZATION"
      label: "GitHub Organization"
      description: "GitHub Organization"
      type: "string"
      default: "camptocamp"
      required: true
    - variable: "GITHUB_CLIENT_ID"
      label: "GitHub Client ID"
      description: "GitHub Application Client ID"
      type: "string"
      required: true
    - variable: "GITHUB_SECRET"
      label: "GitHub Secret"
      description: "GitHub Application Secret"
      type: "password"
      required: true
    - variable: "AUTH_REALM"
      label: "Authentication Realm"
      description: "Authentication Realm for the Registry"
      type: "string"
      default: "https://auth.registry.infra.caas-camptocamp.net:5001"
      required: true

registry:
  health_check:
    port: 5000
    interval: 10000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000

auth:
  health_check:
    port: 5001
    interval: 10000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
